function [Ps,PsFinal] = evaluatePstars(ab)
% evaulates analytical Pstar terms with specific alpha_cBar probability
% lookup table generated by (slow) computation of analytical coefficients
%   (using computePstars in analytical mode):
%   PstarCoefficients = computePstars(nStars,[],'ANALYTIC');
% ** Note that coefficients up to nStars-1 are similar for each nStars)
% ** HOWEVER, the final term is unique for the specific nStars

% BR, 6/25/2015

%{
if(nStars>10)
   disp('WARNING: Only nStars=10 supported, returning that')
   nStars=10;
end
%}

Ps(1) = - ab^4 + 2*ab^3 - 2*ab^2 + ab;
PsFinal(1) = - ab^2 + ab;

Ps(2) = - ab^6 + 4*ab^5 - 6*ab^4 + 5*ab^3 - 3*ab^2 + ab;
PsFinal(2) =  - ab^4 + 4*ab^3 - 5*ab^2 + 2*ab;

Ps(3) = - ab^8 + 6*ab^7 - 15*ab^6 + 20*ab^5 - 16*ab^4 + 9*ab^3 - 4*ab^2 + ab;
PsFinal(3) = - ab^6 + 6*ab^5 - 15*ab^4 + 19*ab^3 - 12*ab^2 + 3*ab;

Ps(4) = - ab^10 + 8*ab^9 - 28*ab^8 + 56*ab^7 - 70*ab^6 + 57*ab^5 - 32*ab^4 + 14*ab^3 - 5*ab^2 + ab;
PsFinal(4) = - ab^8 + 8*ab^7 - 28*ab^6 + 56*ab^5 - 69*ab^4 + 52*ab^3 - 22*ab^2 + 4*ab;

Ps(5) = - ab^12 + 10*ab^11 - 45*ab^10 + 120*ab^9 - 210*ab^8 + 252*ab^7 - 211*ab^6 + 125*ab^5 - 55*ab^4 + 20*ab^3 - 6*ab^2 + ab;
PsFinal(5) =  - ab^10 + 10*ab^9 - 45*ab^8 + 120*ab^7 - 210*ab^6 + 251*ab^5 - 205*ab^4 + 110*ab^3 - 35*ab^2 + 5*ab;

Ps(6) = - ab^14 + 12*ab^13 - 66*ab^12 + 220*ab^11 - 495*ab^10 + 792*ab^9 - 924*ab^8 + 793*ab^7 - 501*ab^6 + 235*ab^5 - 86*ab^4 + 27*ab^3 - 7*ab^2 + ab;
PsFinal(6) = - ab^12 + 12*ab^11 - 6*ab^10 + 220*ab^9 - 495*ab^8 + 792*ab^7 - 923*ab^6 + 786*ab^5 - 480*ab^4 + 200*ab^3 - 51*ab^2 + 6*ab;
 
Ps(7) = - ab^16 + 14*ab^15 - 91*ab^14 + 364*ab^13 - 1001*ab^12 + 2002*ab^11 - 3003*ab^10 + 3432*ab^9 - 3004*ab^8 + 2009*ab^7 - 1022*ab^6 + 399*ab^5 - 126*ab^4 + 35*ab^3 - 8*ab^2 + ab;
PsFinal(7) = - ab^14 + 14*ab^13 - 91*ab^12 + 364*ab^11 - 1001*ab^10 + 2002*ab^9 - 3003*ab^8 + 3431*ab^7 - 2996*ab^6 + 1981*ab^5 - 966*ab^4 + 329*ab^3 - 70*ab^2 + 7*ab;

Ps(8) = - ab^18 + 16*ab^17 - 120*ab^16 + 560*ab^15 - 1820*ab^14 + 4368*ab^13 - 8008*ab^12 + 11440*ab^11 - 12870*ab^10 + 11441*ab^9 - 8016*ab^8 + 4396*ab^7 - 1876*ab^6 + 630*ab^5 - 176*ab^4 + 44*ab^3 - 9*ab^2 + ab;
PsFinal(8) = - ab^16 + 16*ab^15 - 120*ab^14 + 560*ab^13 - 1820*ab^12 + 4368*ab^11 - 8008*ab^10 + 11440*ab^9 - 12869*ab^8 + 11432*ab^7 - 7980*ab^6 + 4312*ab^5 - 1750*ab^4 + 504*ab^3 - 92*ab^2 + 8*ab;
  
Ps(9) = - ab^20 + 18*ab^19 - 153*ab^18 + 816*ab^17 - 3060*ab^16 + 8568*ab^15 - 18564*ab^14 + 31824*ab^13 - 43758*ab^12 + 48620*ab^11 - 43759*ab^10 + 31833*ab^9 - 18600*ab^8 + 8652*ab^7 - 3186*ab^6 + 942*ab^5 - 237*ab^4 + 54*ab^3 - 10*ab^2 + ab;
PsFinal(9) = - ab^18 + 18*ab^17 - 153*ab^16 + 816*ab^15 - 3060*ab^14 + 8568*ab^13 - 18564*ab^12 + 31824*ab^11 - 43758*ab^10 + 48619*ab^9 - 43749*ab^8 + 31788*ab^7 - 18480*ab^6 + 8442*ab^5 - 2934*ab^4 + 732*ab^3 - 117*ab^2 + 9*ab;

PsFinal(10) = - ab^20 + 20*ab^19 - 190*ab^18 + 1140*ab^17 - 4845*ab^16 + 15504*ab^15 - 38760*ab^14 + 77520*ab^13 - 125970*ab^12 + 167960*ab^11 - 184755*ab^10 + 167950*ab^9 - 125925*ab^8 + 77400*ab^7 - 38550*ab^6 + 15252*ab^5 - 4635*ab^4 + 1020*ab^3 - 145*ab^2 + 10*ab;

% Final term has different structure (pass both to KF, it handles)
% PstarCoefficients = Ps(1:nStars-1);
% PstarCoefficients(nStars) = PsFinal(nStars);